# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('ParentCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DAGR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Author', models.CharField(max_length=50, verbose_name='Author')),
                ('CreationTime', models.DateTimeField(verbose_name='Creation Time')),
                ('LastModified', models.DateTimeField(verbose_name='Last Modified')),
                ('Size', models.CharField(max_length=50, verbose_name='Size')),
                ('DeletionTime', models.DateTimeField(verbose_name='Deletion Time')),
                ('HasKids', models.BooleanField(verbose_name='Has Kids')),
            ],
        ),
        migrations.CreateModel(
            name='DAGRCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.Category')),
                ('DAGR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='DAGRChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='DAGR.DAGR')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('Author', models.CharField(max_length=50, verbose_name='Author')),
                ('CreationTime', models.DateTimeField(verbose_name='Creation Time')),
                ('LastModified', models.DateTimeField(verbose_name='Last Modified')),
                ('Size', models.IntegerField(verbose_name='Size')),
                ('Links', models.FileField(upload_to='files/')),
                ('Type', models.CharField(max_length=50, verbose_name='Type')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
    ]
