# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0003_auto_20170503_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagr',
            name='DeletionTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletion Time'),
        ),
        migrations.AlterField(
            model_name='dagr',
            name='LastModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='document',
            name='LastModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR'),
        ),
    ]
