# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0004_auto_20170503_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dagr',
            name='Size',
        ),
    ]
