# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0006_document_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='DAGR',
            field=models.ManyToManyField(through='DAGR.DAGRCategory', to='DAGR.DAGR'),
        ),
    ]
