# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0009_auto_20170504_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dagrcategory',
            old_name='Category',
            new_name='Cat',
        ),
        migrations.RenameField(
            model_name='dagrcategory',
            old_name='DAGR',
            new_name='DA',
        ),
    ]
